version: "2.4"

services:
  odoo:
    build:
      context: ./odoo
      args:
        ODOO_VERSION: "15.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      EMAIL_FROM: "admin@gechcode.com"
      PGDATABASE: &dbname prod
      PGUSER: &dbuser "odoo"
      PROXY_MODE: "true"
      LIST_DB: "true"
    hostname: "gechcode.com"
    tty: true
    volumes:
      - filestore:/var/lib/odoo:z
    labels:
      traefik.backend.buffering.retryExpression: IsNetworkError() && Attempts() < 5
      traefik.docker.network: "inverseproxy_shared"
      traefik.frontend.passHostHeader: "true"
      traefik.port: "8069"

  db:
    image: ghcr.io/tecnativa/postgres-autoconf:14-alpine
    shm_size: 4gb
    environment:
      POSTGRES_DB: *dbname
      POSTGRES_USER: *dbuser
      CONF_EXTRA: |
        work_mem = 512MB
    volumes:
      - db:/var/lib/postgresql/data:z

  smtpfake:
    image: docker.io/mailhog/mailhog

  smtpreal:
    image: ghcr.io/docker-mailserver/docker-mailserver:10
    domainname: "gechcode.com"
    stop_grace_period: 1m
    volumes:
      - mailconfig:/tmp/docker-mailserver:z
      - maildata:/var/mail:z
      - maillogs:/var/log/mail:z
      - maillogssupervisord:/var/log/supervisor:z
      - mailstate:/var/mail-state:z
    cap_add:
      - SYS_PTRACE
    environment:
      DEFAULT_RELAY_HOST: "[smtp.migadu.com]:587"
      DMS_DEBUG: 0
      ENABLE_SRS: 1
      ONE_DIR: 1
      PERMIT_DOCKER: connected-networks
      POSTFIX_INET_PROTOCOLS: ipv4
      POSTFIX_MESSAGE_SIZE_LIMIT: 52428800 # 50 MiB
      RELAY_HOST: "smtp.migadu.com"
      RELAY_PORT: "587"
      RELAY_USER: "admin@gechcode.com"
      SMTP_ONLY: 1
      SRS_DOMAINNAME: "gechcode.com"
      SRS_EXCLUDE_DOMAINS: "gechcode.com"
      SRS_SENDER_CLASSES: envelope_sender,header_sender
