version: '3'

services:
    # ops_front:
  #   container_name: ops_front_local
  #   restart: always
  #   build:  
  #     context: ./ops_front
  #     dockerfile: Dockerfile-local
  #   image: ops_front_image
  #   # depends_on:
  #   #   - agolapi
  #   # volumes:
  #   #   - ./ops_front/nginx:/etc/nginx/conf.d
  #   ports:
  #     - 81:80

  cust_front:
    container_name: cust_front_local_hot
    restart: always
    build:  
      context: .
      dockerfile: Dockerfile-local      
    image: cust_front_image
    volumes:
      - .:/app:z
      - /app/node_modules
    ports:
      - "82:5173"
    environment:
      - PORT=5173

    

    networks:
      portal_oilandgas_network:
        ipv4_address: 172.28.1.3
    # command: npm run dev

  # cust_front:
  #   container_name: cust_front_local
  #   restart: always
  #   build:  
  #     context: ./cust_front
  #     dockerfile: Dockerfile-local
  #   image: cust_front_image
  #   ports:
  #     - "82:80"

networks:
  portal_oilandgas_network:
    external: true